### ISSUE TITLE
About fine-tuning in custom dataset

### ISSUE THREAD

**Issue by davidyang180** [microsoft/GLIP#85]
Based on the chapter ODinW / Custom Dataset Evaluation, I designed the data config like below:
```
DATALOADER:
  ASPECT_RATIO_GROUPING: false
  SIZE_DIVISIBILITY: 32
  DISTRIBUTE_CHUNK_AMONG_NODE: false
DATASETS:
  GENERAL_COPY: 16
  TRAIN_DATASETNAME_SUFFIX: '_grounding'
  USE_OVERRIDE_CATEGORY: True
  USE_CAPTION_PROMPT: True
  REGISTER:
    train:
      img_dir: "open_world"
      ann_file: "open_world/annotations/train.json"
    test:
      img_dir: "open_world"
      ann_file: "open_world/annotations/validation.json"

  TRAIN: ("train",) 
  TEST: ("test",)

INPUT:
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 640
  MIN_SIZE_TRAIN: 640
MODEL:
  ATSS:
    NUM_CLASSES: 1642
  DYHEAD:
    NUM_CLASSES: 1642
  FCOS:
    NUM_CLASSES: 1642
  ROI_BOX_HEAD:
    NUM_CLASSES: 1642
SOLVER:
  CHECKPOINT_PERIOD: 100
  MAX_EPOCH: 12
  WARMUP_ITERS: 0
  IMS_PER_BATCH: 1
TEST:
  EVAL_TASK: 'detection'
  IMS_PER_BATCH: 1
  NUM_CLASSES: 1641
OUTPUT_DIR: 'output'
```
The evaluation process is based on the number of categories in the read data set is 1641, and there is no background class with id, so here MODELS.*.NUM_CLASSES is set to 1642. In this data config, the prompt is not manually changed, and all categories are connected as prompts by default. Finally, I used the following command to perform zero-shot evaluation on the custom dataset.
```
python tools/test_grounding_net.py --config-file configs/pretrain/glip_Swin_T_O365_GoldG.yaml --weight MODEL/glip_tiny_model_o365_goldg_cc_sbu.pth\
      --task_config configs/open_world/val.yaml \
      TEST.IMS_PER_BATCH 1 SOLVER.IMS_PER_BATCH 1 \
      TEST.EVAL_TASK detection \
      DATASETS.TRAIN_DATASETNAME_SUFFIX _grounding \
      DATALOADER.DISTRIBUTE_CHUNK_AMONG_NODE False \
      DATASETS.USE_OVERRIDE_CATEGORY True \
      DATASETS.USE_CAPTION_PROMPT True
```
However, index overflow will be reported during the evaluation process. May I ask what caused this problem and which step I did not configure correctly?
