### ISSUE TITLE
How to do prompt fine-tune in custum dataset.

### ISSUE THREAD

**Issue by Edwardmark** [microsoft/GLIP#9]
I try to do prompt fine-tune in my custum dataset with only one class. So I set the data config like below:
```
DATALOADER:
  ASPECT_RATIO_GROUPING: false
  SIZE_DIVISIBILITY: 32

DATASETS:
  GENERAL_COPY: 16
  CAPTION_PROMPT: '[{"prefix": " ", "name": "cigaret", "suffix": ", tube-shaped product smoked near mouth or holding by finger"}, ]'
  REGISTER:
    train:
      ann_file: '/data/smoke/coco_format_json/coco_train_merge.json'
      img_dir:  ''
    val:
      ann_file: '/data/smoke/coco_format_json/smoke_val_102.json'
      img_dir: '' 
  TEST: ("val",)
  TRAIN: ("train",)
INPUT:
  MAX_SIZE_TEST: 640
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 640
  MIN_SIZE_TRAIN: 640
MODEL:
  ATSS:
    NUM_CLASSES: 2
  DYHEAD:
    NUM_CLASSES: 2
  FCOS:
    NUM_CLASSES: 2
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
SOLVER:
  CHECKPOINT_PERIOD: 100
  MAX_EPOCH: 0
  WARMUP_ITERS: 0
TEST:
  IMS_PER_BATCH: 1

```
Then I try to do inference following the demo (https://colab.research.google.com/drive/12x7v-_miN7-SRiziK3Cx4ffJzstBJNqb?usp=sharing), using the config file generated in ft_task_1/config.yaml, the inference important code is as follows:
```
caption = 'cigaret, tube-shaped product smoked near mouth or holding by finger'

image = cv2.imread(im_path)
result, preds = glip_demo.run_on_web_image(image, caption, 0.5)
```
if using the num_class=2 configuration, it will report a index overflow, so I change the num_class to 81 as default, then the code can run without errors, but no preds for other object like "mouth"/"finger", that is strange.

Could you tell me the right way to do prompt fine-tuning and after fine-tuning, the right way to infernce the new model?

Thanks.
